services:
  - type: web
    name: votex-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: votex-data
      mountPath: /opt/render/project/src/backend
      sizeGB: 1
